### ISSUE TITLE
User Defined Functions in initial_hive_commands_*

### ISSUE THREAD

**Issue by karatemir** [SpatialDataCommons/CDR-analysis-tools-hadoop#1]
Hi,

I am checking out how your repo is structured and have some questions. I haven't used java before so I would really appreciate it if you can clarify some points for me.

As an example for route interpolation the following query is executed:
`insert overwrite table {provider_prefix}_cdr_by_uid_trip_routing_array_apd partition (pdt)
select uid,f_routing(uid,arr,"{osm}","{voronoi}"), pdt
from {provider_prefix}_cdr_by_uid_trip_realloc_array_apd
where (size(arr)>0 and  size(arr)<={max_size_interpolation})`

which uses `f_routing` and that function is in turn defined in `initial_hive_commands_interpolation.json` as:
`"create temporary function f_routing         as 'jp.ac.ut.csis.pflow.turkcell.hive.udf.TurkcellRoutingUDF'"`

Am I supposed to have these Hive user defined functions somewhere? I downloaded PFlow from sekilab github, but can't find any such related functions.

Similarly some functions like FindPolygon are defined as `"create temporary function FindPolygon as 'com.apichon.mobility.hive.udf.FindPolygon'"`, which are UDFs written by Dr. Apichon Witayangkurn I assume.

Thanks a lot in advance.

**Comment by apichon** [comment]
i have already uploaded lib. please check folder lib.
